sudo: required
dist: trusty
language: node_js

node_js:
  - 'stable'

install:
  - npm install

before_script:
  - node ./external/Signer.js &
  - mkdir base-node
  - cd base-node
  - git clone https://github.com/bitclave/base-node.git
  - ls
  - sleep 2

script:
  - npm run coveralls
