sudo: required
dist: trusty
language: node_js

node_js:
  - 'stable'

install:
  - npm install

before_script:
  - mkdir base-node
  - cd base-node
  - git clone git@github.com:bitclave/base-node.git
  - ls


script:
  - npm run coveralls
